language: python

python:
  - '2.7'

services:
  - postgresql

addons:
  postgresql: '9.4'

virtualenv:
  system_site_packages: true

install:
  - sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list
  - sudo apt-get update -y
  - sudo apt-get install python-gdal gdal-bin binutils
  - export C_INCLUDE_PATH=/usr/include/gdal
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal

before_script:
  - psql template1 postgres -c 'create extension hstore;'
  - psql -c 'create database geokey;' -U postgres
  - psql -U postgres -d geokey -c "create extension postgis;"
  - pip install geokey
  - pip install -r travis/requirements.txt
  - pip install -e .
  - python travis/manage.py migrate

script:
  - coverage run --source=geokey_export travis/manage.py test geokey_export

after_success:
  - coveralls

deploy:
  provider: pypi
  user: excites
  password:
    secure: nTpl3JBc5eOLNe0LrM3BozdF+USqWGsLr52FJ7p+9kU4pRWxS8U4gdcIAuwCB1ewrIJJOOc3333lZmXsp6xbjf/sgST9QDwX0TAAlC1lM1IiwCeosrILq6KTrdo7okwyXSm3ggbtlKrL/v02Hf3DrABTPV3j32861mXF+gEBsCCFue+dqAshKsiQkgn7PGMZSaAyYJfeGAcXt97yuBXpnAeJunar31UmaBCwZCyA6uSiiC8qUpmy9HjalPotjXLSF6zEJEoOxfIzJFhQ4k2FsAWAEdwAt1ETlA9s8LF6zYEsGqFKiSOBgsIiYjBAdekbjRBEOx9OOw1I1HdKIV4uqKOlBO4FKIIwgZZz74G3dgAPPFeEwXUNt8zIrxmEMGQVA2K6IJotvmISHpniiqk8YTmGX3w2lNQ/FzIekbpnSQoQwGk0krccMqhM4iiHTotQ6gqJu/EPrAkgZJ1LO2r/TNFSh/Ybj12/MZOaZEpucp+ZsE0BSkvOMx8Bf0B/yg9w01WP4hYHls/oUDK3fn8+NYQmUJdnzu61lvh1O38Ai2kdh2sfJRFOMs/zZqPVp0hfNnq7k9aNhcob23L99T7JEdY0isYO4wfkghru0mcJNuIoTXUsC1CPOGOy5F5/Qhy3hJechYfq8GuUCFqNNtks2K9t5pDIJIeAvtZS6eGctn8=
  on:
    tags: true
    branch: master
